### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by michaelwsherman** [fpaupier/tensorflow-serving_sidecar#13]
Hi.

It would be helpful if this repo had a LICENSE file, so terms of reuse were clear. Instructions are here: https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository .

I think you have a cool example, and I'd like to share it with some folks here at Google, but we can't do anything with it without a license.

Thanks!

**Comment by fpaupier** [comment]
Indeed. This project is MIT licensed. I'll update it.
