### ISSUE TITLE
cannot import name 'plot_util'

### ISSUE THREAD

**Issue by ashwini-git** [fpaupier/tensorflow-serving_sidecar#3]
while running client.py script , i am getting error as - cannot import name 'plot_util'. 
i do not see 'plot_util.py' file under object_detection/utils. 

Let me know your views.
Thanks

**Comment by ashwini-git** [comment]
issue was resolved.

**Comment by seth814** [comment]
In case someone else is having this issue, I was able to resolve doing the following. If you go to the installation docs, https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

You will see a protobuf compilation step. From tensorflow-serving-sidecar:

`protoc object_detection/protos/*.proto --python_out=.`
